import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "./page.module.css"
import Link from "next/link";
import Moon from "./Moon/page";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function DestinationLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <main className={styles.main}>
            <div className={styles.pageTitle}><span className={styles.pageNum}>01</span>PICK UP YOUR DESTINATION</div>
            <div className={styles.pageMainArea}>
                {children} 
            </div>
        </main>
    );
}
